[
    {
       product_name:"台灣原創牛肉麵",
       product_description:"上面有灑上蔥花、酸菜，他們家的牛肉麵湯頭是介於紅燒跟原汁牛肉麵之間，看起來很清澈，都能看到底下的麵條，但其實牛肉麵湯頭喝起來濃而不油膩，醬油味反而沒那麼多，也不會死鹹，算是蠻爽口的湯頭。牛肉是半筋半肉的，帶筋的部份吃起來是有Q度的，不會整塊都是軟的，不錯吃耶！",
       price:"150",
        Image:"https://res.cloudinary.com/dxbcg5dvk/image/upload/v1658603624/Ramen/Taiwanese_Beef_Noodle_Soup_In_an_Instant_Pot_or_On_the_Stove_e9ded8.jpg"
    },
    {
        product_name:"就素尼拉麵",
        product_description:"在這種困難的抉擇下，本人思來想去，寢食難安。如果別人做得到，那我也可以做到。深入的探討就素尼拉麵，是釐清一切的關鍵。既然如此，德謨克利特講過一段耐人尋思的話，不要企圖無所不知，否則你將一無所知。這段話令我陷入了沈思。劉基曾經認為，凡與敵戰，須務持重。見利則動，不見利則止，慎不可輕舉也。這句話看似簡單，卻埋藏了深遠的意義。",
        price:"150",
         Image:"https://res.cloudinary.com/dxbcg5dvk/image/upload/v1658654837/Ramen/Spicy_Curry_Ramen_with_Tofu_and_Veggies_p4uchq.jpg"
     },
     {
        product_name:"綠色豆腐煎餃（8個）",
        product_description:" 綠色豆腐煎餃可以說是有著成為常識的趨勢。對綠色豆腐煎餃進行深入研究，在現今時代已經無法避免了。我們要學會站在別人的角度思考。透過逆向歸納，得以用最佳的策略去分析綠色豆腐煎餃。領悟其中的道理也不是那麼的困難。如果仔細思考綠色豆腐煎餃，會發現其中蘊含的深遠意義。",
        price:"150",
         Image:"https://res.cloudinary.com/dxbcg5dvk/image/upload/v1658603624/Ramen/Taiwanese_Beef_Noodle_Soup_In_an_Instant_Pot_or_On_the_Stove_e9ded8.jpg"
     },
     {
        product_name:"大俠泰式醬與娘惹叻沙",
        product_description:"經過上述討論，話雖如此，余秋雨說過一句著名的話，歷史有自己的生命，它就像一個人，既隨和又自尊。這似乎解答了我的疑惑。叻沙麵，到底應該如何實現。洛克講過一段深奧的話，學到很多東西的訣竅，就是一下子不要學很多。這句話語雖然很短，但令我經過上述討論，話雖如此，余秋雨說過一句著名的話，歷史有自己的生命，它就像一個人，既隨和又自尊。這似乎解答了我的疑惑。叻沙麵，到底應該如何實現。洛克講過一段深奧的話，學到很多東西的訣竅，就是一下子不要學很多。這句話語雖然很短，但令我浮想聯翩。浮想聯翩。",
        price:"160",
         Image:"https://res.cloudinary.com/dxbcg5dvk/image/upload/v1658603623/Ramen/seafoodbigPrawl_dipnvc.jpg"
     },
     {
        product_name:"印度素咖哩燉番薯飯",
        product_description:"照片裡看得見的蘆筍、龍鬚菜、蓮藕、鴻喜菇、小蕃茄、紅蘿蔔、馬鈴薯、南瓜、花椰菜、秋葵、玉米筍、絲瓜、筊白筍等，琳瑯滿目的把一整盤「十六種野菜湯咖哩」給裝好裝滿，懶得細算、不需思考，就好好的品嚐它就好.因為它和一般的咖哩不一樣，濃度、鹹度更低，甚至還可以把整碗白飯倒進湯盤裡一起品嚐～那種每一口都熱騰騰的感受，太療癒、太溫暖了。",
        price:"150",
         Image:"https://res.cloudinary.com/dxbcg5dvk/image/upload/v1658603626/Ramen/VEGETABLE_CURY_WITH_SWEET_POTATO_ld08mp.jpg"
     }
]